### ISSUE TITLE
Add request context to validation

### ISSUE THREAD

**Issue by Clement3** [go-goyave/goyave#136]
Hello, firstly thank you for this project.

## Proposal

Add the context `goyave.Request` in the validation.

This gives the possibility to create custom validations with parameters from the Request like the user.

Current custom validation from the documentation:
```
func validateCustomFormat(field string, value interface{}, parameters []string, form map[string]interface{}) bool {
    str, ok := value.(string)

    if ok { // The data under validation is a string
        return regexp.MustCompile(parameters[0]).MatchString(str)
    }

    return false // Cannot validate this field
}
```

Proposal:
```
func validateUserIsAdmin(request *Goyave.Request, field string, value interface{}, parameters []string, form map[string]interface{}) bool {    
    if value != nil {
        user := request.User.(*model.User)

        userIsAdmin := user.isAdmin
    
        return userIsAdmin
    }
    
    return true
}
```

With the fields in Request.Extra this opens more possibility to create validations that match use cases.

### Possible drawbacks

A changes in the organization of structures to avoid cyclical imports.

**Comment by System-Glitch** [comment]
I like the idea but this is a breaking change. The function signature is also already pretty heavy with lots of parameters. If I were to change it, I would probably create a `validation.Context` struct containing everything the validators could need.

About your example, this is a wrong usage of validator. You are checking for permissions, and that should take place in middleware. That is because a validator returning false will result in a `http.StatusUnprocessableEntity`, while you should use `http.StatusUnauthorized` instead.

I don't think that change would require a reorganization of the structure because we could just pass the `request.Extra` map to the validator, without the need for an import of the main package. I don't think validators need (nor should) get any other information from the request to avoid them going beyond their primary goal.

**Comment by Clement3** [comment]
Sorry for the late response.
Indeed, maybe it wasn’t the best example to give, but you understood what I needed.
Your solution allows to have custom fields without having to pass the Request entirely which solve the problem.
